BoschWebsite/urls.py
from django.urls import path
from . import views

app_name = 'BoschWebsite'
urlpatterns = [
    # /BoschWebsite/
    path('', views.index, name='index'),
    # /BoschWebsite/2/
    path('<int:pk>/', views.DriverDetail.as_view(), name='driverdetail'),
    # /BoschWebsite/2/Team/
    path('<int:pk>/Team/', views.TeamDetail.as_view(), name='teamdetail'),
    # /BoschWebsite/2/Track/
    path('<int:pk>/Track/', views.TrackDetail.as_view(), name='track'),
    # /BoschWebsite/overview
    path('Overview', views.overview, name='overview'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('BoschWebsite/', include('BoschWebsite.urls')),
    path('admin/', admin.site.urls),
]

BoschWebsite/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.

# Saving Data of a Team
class Team(models.Model):
    name_text = models.CharField(max_length=50)
    symbol = models.CharField(max_length=300)
    wins = models.IntegerField(default=0)
    poles = models.IntegerField(default=0)
    titles = models.IntegerField(default=0)
    titles_drivers = models.IntegerField(default=0)
    titles_constructors = models.IntegerField(default=0)
    boss = models.CharField(max_length=100)
    start_date = models.DateField(auto_now_add=False, auto_now=False)
    boss_image = models.CharField(max_length=300, default=0)

    # Instead of showing Team (1) in shell now it shows e.g. Team McLaren
    # Same in admin website when Deleting (http://127.0.0.1:8000/admin/)
    def __str__(self):
        return self.name_text


class Driver(models.Model):
    name_text = models.CharField(max_length=100, unique=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, default="", null=True, blank=True)
    age = models.IntegerField(default=0)
    wins = models.IntegerField(default=0)
    poles = models.IntegerField(default=0)
    titles = models.IntegerField(default=0)
    start_date = models.DateField(auto_now_add=False, auto_now=False)
    driver_image = models.CharField(max_length=300)

    # Instead of showing Driver (1) in shell now it shows e.g. Driver Lando Norris
    # Same in admin website when Deleting (http://127.0.0.1:8000/admin/)
    def __str__(self):
        return self.name_text


# Saving Data of a Track
class Track(models.Model):
    name_text = models.CharField(max_length=50)
    laps = models.IntegerField(default=0)
    lapRecord = models.TimeField()
    sector1 = models.TimeField()
    sector2 = models.TimeField()
    sector3 = models.TimeField()
    length = models.FloatField(default=0)
    layout = models.CharField(max_length=300)

    # Instead of showing Track (1) in shell now it shows e.g. Track Melbourne
    # Same in admin website when Deleting (http://127.0.0.1:8000/admin/)
    def __str__(self):
        return self.name_text

BoschWebsite/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from .models import Team, Driver, Track


# Create your views here.
def index(request):
    return render(request, 'BoschWebsite/index.html')


# Create your views here.
def overview(request):
    return render(request, 'BoschWebsite/overview.html')


# Details about the Drivers are shown here
class DriverDetail(generic.DetailView):
    model = Driver
    template_name = 'BoschWebsite/driverdetail.html'


# Details about the Teams are shown here
class TeamDetail(generic.DetailView):
    model = Team
    template_name = 'BoschWebsite/teamdetail.html'


# Details about the Tracks are shown here
class TrackDetail(generic.DetailView):
    model = Track
    template_name = 'BoschWebsite/track.html'


# Static file needed for css to work
def css(request):
    return render(request, 'BoschWebsite/index.html')

BoschWebsite/templates/BoschWebsite/driverdetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}">

    <title>{{ driver.name_text }}</title>
</head>
<body style="width: 100%; height: 100%; overflow-x: hidden">
<div class="navbar">
    <div class="symbol-div">
        <a href="{% url 'BoschWebsite:index' %}">
            <img class="f1-symbol" src="https://upload.wikimedia.org/wikipedia/commons/4/45/F1_logo.svg"></a>
    </div>

    <div class="drivermenu">
        <button class="drivermenubtn">Drivers</button>
        <div class="dropdown-driver">
            {% if latest_driver_list %}
                {% for driver in latest_driver_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:driverdetail' driver.id %}">
                        <button class="driverbtn">
                            {{ driver.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Driver available</p>
            {% endif %}
        </div>
    </div>
    <div class="teammenu">
        <button class="teammenubtn">Teams</button>
        <div class="dropdown-team">
            {% if latest_team_list %}
                {% for team in latest_team_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                        <button class="teambtn" style="cursor: pointer">
                            {{ team.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Team available</p>
            {% endif %}
        </div>
    </div>
    <div class="trackmenu">
        <button class="trackmenubtn">Tracks</button>
        <div class="dropdown-track">
            {% if latest_track_list %}
                {% for track in latest_track_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:track' track.id %}">
                        <button class="trackbtn" style="cursor: pointer">
                            {{ track.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Track available</p>
            {% endif %}
        </div>
    </div>

    <div class="overviewmenu">
        <a href="{% url 'BoschWebsite:overview' %}">
            <button class="overviewmenubtn" style="cursor: pointer">Overview</button>
        </a>
    </div>

</div>

<h1>{{ driver.name_text }}</h1>
<div>
    <img src="{{ driver.driver_image }}" style="width: 300px; height: 300px; border-radius: 20px">
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 300px">
        <div class="divinfo" style="width: 150px; margin-right:10px;">
            <label class="driverdetaillabel" style="position:relative; bottom: 10px; left: 3px">Team</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 15px; left: 15px">{{ driver.team }}</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel" style="position:relative; bottom: 10px; left: 3px">Wins</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 15px; left: 15px">{{ driver.wins }}</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 200px; margin-top: 20px">
        <div class="divinfo" style="width: 100px; margin-right:10px;">
            <label class="driverdetaillabel" style="position:relative; bottom: 10px; left: 3px">Poles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 15px; left: 15px">{{ driver.poles }}</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel" style="position:relative; bottom: 10px; left: 3px">Titles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 15px; left: 15px">{{ driver.titles }}</p>
        </div>
    </div>

    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 200px; margin-top: 20px">
        <div class="divinfo" style="width: 200px; margin-right:10px;">
            <label class="driverdetaillabel" style="position:relative; bottom: 10px; left: 3px">First Race</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 15px; left: 15px">{{ driver.start_date }}</p>
        </div>
    </div>

</div>

</body>
</html>

BoschWebsite/templates/BoschWebsite/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}">
    <title>F1Homepage</title>
</head>
<body style="width: 100%; height: 100%; overflow-x: hidden">
<div class="navbar">
    <div class="symbol-div">
        <a href="{% url 'BoschWebsite:index' %}">
            <img class="f1-symbol" src="https://upload.wikimedia.org/wikipedia/commons/4/45/F1_logo.svg"></a>
    </div>

    <div class="drivermenu">
        <button class="drivermenubtn">Drivers</button>
        <div class="dropdown-driver">
            {% if latest_driver_list %}
                {% for driver in latest_driver_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:driverdetail' driver.id %}">
                        <button class="driverbtn">
                            {{ driver.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Driver available</p>
            {% endif %}
        </div>
    </div>
    <div class="teammenu">
        <button class="teammenubtn">Teams</button>
        <div class="dropdown-team">
            {% if latest_team_list %}
                {% for team in latest_team_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                        <button class="teambtn" style="cursor: pointer">
                            {{ team.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Team available</p>
            {% endif %}
        </div>
    </div>
    <div class="trackmenu">
        <button class="trackmenubtn">Tracks</button>
        <div class="dropdown-track">
            {% if latest_track_list %}
                {% for track in latest_track_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:track' track.id %}">
                        <button class="trackbtn" style="cursor: pointer">
                            {{ track.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Track available</p>
            {% endif %}
        </div>
    </div>

    <div class="overviewmenu">
        <a href="{% url 'BoschWebsite:overview' %}">
            <button class="overviewmenubtn" style="cursor: pointer">Overview</button>
        </a>
    </div>

</div>
<div>
    <!--NO Switch statements in Django??-->

    {% if latest_team_list %}
        {% for team in latest_team_list %}
            <!--dynamically linking websites-->
            {% if team.name_text == "McLaren" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #ff8000 0%, #47c7fc 100%); border-image-source: linear-gradient(to left, #ff8000 0%, #47c7fc 100%)">

            {% elif team.name_text == "Mercedes" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #00d2be 0%, #c6c6c6 100%); border-image-source: linear-gradient(to left, #00d2be 0%, #c6c6c6 100%)">

            {% elif team.name_text == "Ferrari" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #dc0000 0%, #111111 100%); border-image-source: linear-gradient(to left, #dc0000 0%, #111111 100%)">

            {% elif team.name_text == "Red Bull Racing" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #0600ef 0%, #ffc800 100%); border-image-source: linear-gradient(to left, #0600ef 0%, #ffc800 100%)">

            {% elif team.name_text == "Alpine" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #0090ff 0%, #fd4bc7 100%); border-image-source: linear-gradient(to left, #0090ff 0%, #fd4bc7 100%)">

            {% elif team.name_text == "Haas" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #ed1a3b 0%, #ffffff 100%); border-image-source: linear-gradient(to left, #ed1a3b 0%, #ffffff 100%)">

            {% elif team.name_text == "Aston Martin" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #00594f 0%, #cedc00 100%); border-image-source: linear-gradient(to left, #00594f 0%, #cedc00 100%)">

            {% elif team.name_text == "AlphaTauri" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #00293f 0%, #f1f3f4 100%); border-image-source: linear-gradient(to left, #00293f 0%, #f1f3f4 100%)">

            {% elif team.name_text == "Alfa Romeo" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #981e32 0%, #f9f9f8 100%); border-image-source: linear-gradient(to left, #981e32 0%, #f9f9f8 100%)">

            {% elif team.name_text == "Williams" %}
                <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                <div class="homepageteam"
                     style="background: linear-gradient(to right, #041e42 0%, #00a3e0 100%); border-image-source: linear-gradient(to left, #041e42 0%, #00a3e0 100%)">

            {% endif %}

        <p class="teamname">{{ team.name_text }}</p>
        <div class="divimage">
            <img src="{{ team.symbol }}" style="width: 200px; height: 100px; ">
        </div><br><br><br>
        <div class="divboss">
            <img src="{{ team.boss_image }}" style="width: 200px; height: 150px; ">
            <p>Boss: {{ team.boss }}</p>
        </div>
        <div class="divdivinfo" style="bottom: 300px;">
            <div class="divinfo" style="width: 100px">
                <label class="labelinfo">Wins</label>
                <p class="teaminfo">{{ team.wins }} Wins</p>
            </div>
            <div class="divinfo" style="width: 120px; margin-left: 150px; margin-top: -44px">
                <label class="labelinfo">Pole Positions</label>
                <p class="teaminfo">{{ team.poles }} Poles</p>
            </div>
        </div>
        <div class="divdivinfo" style=" bottom: 285px">
            <div class="divinfo" style="width: 125px">
                <label class="labelinfo">First Race</label>
                <p class="teaminfo">{{ team.start_date }}</p>
            </div>
            <div class="divinfo" style="width: 100px; margin-left: 150px; margin-top: -44px">
                <label class="labelinfo">Titles</label>
                <p class="teaminfo">{{ team.titles }} Titles</p>
            </div>
        </div>
        <div class="divdivinfo" style="bottom: 260px">
            <div class="divinfo" style="width: 200px">
                <label class="labelinfo">Drivers-Championships</label>
                <p class="teaminfo">{{ team.titles_drivers }} Drivers Titles</p>
            </div>
            <div class="divinfo" style="width: 250px; margin-left: 230px; margin-top: -44px">
                <label class="labelinfo">Constructors-Championships</label>
                <p class="teaminfo">{{ team.titles_constructors }} Constructors
                    Titles</p>
            </div>

        </div>
        </div>
        </a>
        </div>

        {% endfor %}
    {% else %}
        <p>No Team available</p>
    {% endif %}
    </a>
</body>
</html>

BoschWebsite/templates/BoschWebsite/teamdetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'driver.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}">

    <title>{{ team.name_text }}</title>
</head>
<body style="width: 100%; height: 100%; overflow-x: hidden">
<div class="navbar">
    <div class="symbol-div">
        <a href="{% url 'BoschWebsite:index' %}">
            <img class="f1-symbol" src="https://upload.wikimedia.org/wikipedia/commons/4/45/F1_logo.svg"></a>
    </div>

    <div class="drivermenu">
        <button class="drivermenubtn">Drivers</button>
        <div class="dropdown-driver">
            {% if latest_driver_list %}
                {% for driver in latest_driver_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:driverdetail' driver.id %}">
                        <button class="driverbtn">
                            {{ driver.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Driver available</p>
            {% endif %}
        </div>
    </div>
    <div class="teammenu">
        <button class="teammenubtn">Teams</button>
        <div class="dropdown-team">
            {% if latest_team_list %}
                {% for team in latest_team_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                        <button class="teambtn" style="cursor: pointer">
                            {{ team.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Team available</p>
            {% endif %}
        </div>
    </div>
    <div class="trackmenu">
        <button class="trackmenubtn">Tracks</button>
        <div class="dropdown-track">
            {% if latest_track_list %}
                {% for track in latest_track_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:track' track.id %}">
                        <button class="trackbtn" style="cursor: pointer">
                            {{ track.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Track available</p>
            {% endif %}
        </div>
    </div>

    <div class="overviewmenu">
        <a href="{% url 'BoschWebsite:overview' %}">
            <button class="overviewmenubtn" style="cursor: pointer">Overview</button>
        </a>
    </div>

</div>

<h1>{{ team.name_text }}</h1>
<div>
    <img src="{{ team.symbol }}" style="width: 400px; height: 300px; border-radius: 20px">
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 300px">
        <div class="divinfo" style="width: 150px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black; position:relative; bottom: 10px; left: 3px">Team</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.name_text }}</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel"
                   style="color: black; position:relative; bottom: 10px; left: 3px">Wins</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.wins }}</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 200px; margin-top: 20px">
        <div class="divinfo" style="width: 100px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Poles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.poles }}</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Titles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.titles }}</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 400px; margin-top: 20px">
        <div class="divinfo" style="width: 130px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Drivers Titles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.titles_drivers }}</p>
        </div>
        <div class="divinfo" style="width: 160px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Constructors Titles</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.titles_constructors }}</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 400px; bottom: 300px; width: 200px; margin-top: 20px">
        <div class="divinfo" style="width: 160px; margin-right:10px;">
            <label class="driverdetaillabel" style="color: black;  position:relative; bottom: 10px; left: 3px">First
                Race</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ team.start_date }}</p>
        </div>
    </div>

</div>

</body>
</html>

BoschWebsite/templates/BoschWebsite/track.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'driver.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}">
    <title>{{ track.name_text }} Page</title>
</head>
<body style="width: 100%; height: 100%; overflow-x: hidden">
<div class="navbar">
    <div class="symbol-div">
        <a href="{% url 'BoschWebsite:index' %}">
            <img class="f1-symbol" src="https://upload.wikimedia.org/wikipedia/commons/4/45/F1_logo.svg"></a>
    </div>

    <div class="drivermenu">
        <button class="drivermenubtn">Drivers</button>
        <div class="dropdown-driver">
            {% if latest_driver_list %}
                {% for driver in latest_driver_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:driverdetail' driver.id %}">
                        <button class="driverbtn">
                            {{ driver.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Driver available</p>
            {% endif %}
        </div>
    </div>
    <div class="teammenu">
        <button class="teammenubtn">Teams</button>
        <div class="dropdown-team">
            {% if latest_team_list %}
                {% for team in latest_team_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:teamdetail' team.id %}">
                        <button class="teambtn" style="cursor: pointer">
                            {{ team.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Team available</p>
            {% endif %}
        </div>
    </div>
    <div class="trackmenu">
        <button class="trackmenubtn">Tracks</button>
        <div class="dropdown-track">
            {% if latest_track_list %}
                {% for track in latest_track_list %}
                    <!--dynamically linking websites-->
                    <a href="{% url 'BoschWebsite:track' track.id %}">
                        <button class="trackbtn" style="cursor: pointer">
                            {{ track.name_text }}
                        </button>
                    </a>
                {% endfor %}
            {% else %}
                <p>No Track available</p>
            {% endif %}
        </div>
    </div>

    <div class="overviewmenu">
        <a href="{% url 'BoschWebsite:overview' %}">
            <button class="overviewmenubtn" style="cursor: pointer">Overview</button>
        </a>
    </div>

</div>

<h1>{{ track.name_text }}</h1>
<div>
    <img src="{{ track.layout }}" style="width: 500px; height: 300px; border-radius: 20px">
    <div style="display: flex; position: relative; left: 525px; bottom: 300px; width: 300px">
        <div class="divinfo" style="width: 150px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black; position:relative; bottom: 10px; left: 3px">Length</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.length }} km</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel"
                   style="color: black; position:relative; bottom: 10px; left: 3px">Laps</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.laps }}</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 525px; bottom: 300px; width: 300px; margin-top: 20px">
        <div class="divinfo" style="width: 100px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Lap Record</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.lapRecord|time:"i:s" }}
                min</p>
        </div>
        <div class="divinfo" style="width: 100px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Sector 1</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.sector1|time:"i:s" }}
                sec</p>
        </div>
    </div>
    <div style="display: flex; position: relative; left: 525px; bottom: 300px; width: 400px; margin-top: 20px">
        <div class="divinfo" style="width: 130px; margin-right:10px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Sector 2</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.sector2|time:"i:s" }}
                sec</p>
        </div>
        <div class="divinfo" style="width: 160px;">
            <label class="driverdetaillabel"
                   style="color: black;  position:relative; bottom: 10px; left: 3px">Sector 3</label>
            <p class="driverinfo"
               style="color: black; position: relative; bottom: 20px; left: 15px">{{ track.sector3|time:"i:s" }}
                sec</p>
        </div>
    </div>
</div>


</body>
</html>